#!/bin/bash

# 已知问题: 同时运行多个如下脚本可能会导致未知的指令无法成功执行, 启动时切勿携带 `&` 符号后台运行

workpath="/for/"
screen_name="bar"
cmd="command"

echo -e "screen start: $screen_name, $cmd\n"

screen -dmS "$screen_name"

while true; do
    if screen -ls | grep -q "$screen_name"; then
        break;
    fi
done
# sleep 1s  # sleep to wait screen start

screen -x -S "$screen_name" -p 0 -X stuff "cd \"$workpath\" && $cmd"
screen -x -S "$screen_name" -p 0 -X stuff $'\n'
